export enum StudentStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  AWAITING_ARRIVAL = 'AWAITING_ARRIVAL',
  ARRIVED = 'ARRIVED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
}
